export const DRIVER_MODULE = 'DRIVER';
export enum DRIVER_ACTION {
  /*
    UPLOAD RELATED
  */
  UPLOAD_CARD_FRONT = 'UPLOAD_CARD_FRONT',
  UPLOAD_CARD_BACK = 'UPLOAD_CARD_BACK',
  UPLOAD_DRIVER_LICENSE = 'UPLOAD_DRIVER_LICENSE',
  UPLOAD_TRUCK_CERTIFICATE = 'UPLOAD_TRUCK_CERTIFICATE',
  UPLOAD_BUSINESS_LICENSE = 'UPLOAD_BUSINESS_LICENSE',
  UPLOAD_COMPANY_ICON = 'UPLOAD_COMPANY_ICON',
  DELETE_FILE = 'DELETE_FILE',

  /*
    PROFILE RELATED
  */
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',

  /*
    ORDER RELATED
  */
  SEND_TRACKING = 'SEND_TRACKING',
  CANCEL_ORDER = 'CANCEL_ORDER',
}
