version: '3'
services:
  db-tada:
    image: 'postgres:latest'
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - './db_1:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - '${DB_PORT}'
