export const ORDER_MODULE = 'ORDER';
export enum ORDER_ACTION {
  UPDATE_ORDER = 'UPDATE_ORDER',
  UPDATE_STATUS_ORDER = 'UPDATE_STATUS_ORDER',
  DELETE_ONE_ORDER = 'DELETE_ONE_ORDER',
  ADD_TRUCK_TO_ORDER = 'ADD_TRUCK_TO_ORDER',
  ADD_DRIVER_TO_ORDER = 'ADD_DRIVER_TO_ORDER',
  REMOVE_DRIVER_FROM_ORDER = 'REMOVE_DRIVER_FROM_ORDER',
  REMOVE_TRUCK_FROM_ORDER = 'REMOVE_TRUCK_FROM_ORDER',
  DELETE_FOLDER_FROM_ORDER = 'DELETE_FOLDER_FROM_ORDER',
  DELETE_FILE_FROM_ORDER = 'DELETE_FILE_FROM_ORDER',
  UPLOAD_DOCUMENT_TO_ORDER = 'UPLOAD_DOCUMENT_TO_ORDER',
  DELETE_NOTE_FROM_ORDER = 'DELETE_NOTE_FROM_ORDER',
  UPDATE_PAYMENT_DONE = 'UPDATE_PAYMENT_DONE',
  FIND_NEW_TRUCK = 'FIND_NEW_TRUCK',
  ADD_NOTE_TO_ORDER = 'ADD_NOTE_TO_ORDER',
  IMPORT_ORDER = 'IMPORT_ORDER',
  UPDATE_COMMISSION = 'UPDATE_COMMISSION',
}
