export enum SERVICE_TYPE {
  TRAILOR_TRACTOR_TRUCK = 'TRAILOR_TRACTOR_TRUCK',
  NORMAL_TRUCK_VAN = 'NORMAL_TRUCK_VAN',
  NON_MOTORIZED_VEHICLE = 'NON_MOTORIZED_VEHICLE',
  CONCATENATED_GOODS = 'CONCATENATED_GOODS',
  CONTRACT_CAR = 'CONTRACT_CAR',
}

export enum TRUCK_TYPE_DEFAULT {
  ANY,
  FREEZING_BODY,
  MINI_VAN,
  MEZZAN,
  CLOSED_BODY,
  TARPAULIN_COVER,
  GRID_AND_TARPAULIN_COVER,
  WING_BODY,
  FOR_RETAILER,
  WITHOUT_BODY,
  WITH_LIFT,
  DUMP_TRUCK,
  TANK_TRUCK,
}

export enum NON_MOTORIZED_TYPE {
  '2B' = '2B',
  '3B' = '3B',
}

export enum NON_MOTORIZED_TYPE_FILTER {
  'ANY' = 'ANY',
  '2B' = '2B',
  '3B' = '3B',
}

export enum NON_MOTORIZED_TYPE_IMPORT {
  '2B' = '2B',
  '3B' = '3B',
}

export enum NON_MOTORIZED_PAYLOAD {
  ANY = '0',
  LESS_THAN_THREE_KG = 'less_than_3kg',
  THREE_TO_TEN_KG = '3_10kg',
  TEN_TO_TWENTY_FIVE_KG = '10_25kg',
  TWENTY_FIVE_TO_FIFTY_KG = '25_50kg',
  FIFTY_TO_ONE_HUNDRED_KG = '50_100kg',
  ONE_HUNDRED_TO_FIVE_HUNDRED_KG = '100_500kg',
  MORE_THAN_FIVE_HUNDRED_KG = 'more_than_500kg',
}

export enum NON_MOTORIZED_PAYLOAD_IMPORT {
  'Bất kì' = NON_MOTORIZED_PAYLOAD.ANY,
  'Any' = NON_MOTORIZED_PAYLOAD.ANY,
  '<3 kg' = NON_MOTORIZED_PAYLOAD.LESS_THAN_THREE_KG,
  '3-10 kg' = NON_MOTORIZED_PAYLOAD.THREE_TO_TEN_KG,
  '10-25 kg' = NON_MOTORIZED_PAYLOAD.TEN_TO_TWENTY_FIVE_KG,
  '25-50 kg' = NON_MOTORIZED_PAYLOAD.TWENTY_FIVE_TO_FIFTY_KG,
  '50-100 kg' = NON_MOTORIZED_PAYLOAD.FIFTY_TO_ONE_HUNDRED_KG,
  '100-500 kg' = NON_MOTORIZED_PAYLOAD.ONE_HUNDRED_TO_FIVE_HUNDRED_KG,
  '>500 kg' = NON_MOTORIZED_PAYLOAD.MORE_THAN_FIVE_HUNDRED_KG,
}

export enum TRUCK_TYPE_IMPORT {
  'Any' = TRUCK_TYPE_DEFAULT.ANY,
  'Mini-Van' = TRUCK_TYPE_DEFAULT.MINI_VAN,
  'Truck with tarpaulin cover' = TRUCK_TYPE_DEFAULT.TARPAULIN_COVER,
  'Truck with grid and tarpaulin cover' = TRUCK_TYPE_DEFAULT.GRID_AND_TARPAULIN_COVER,
  'Truck with wing-body' = TRUCK_TYPE_DEFAULT.WING_BODY,
  'Truck for retailer' = TRUCK_TYPE_DEFAULT.FOR_RETAILER,
  'Truck without body' = TRUCK_TYPE_DEFAULT.WITHOUT_BODY,
  'Dump truck' = TRUCK_TYPE_DEFAULT.DUMP_TRUCK,
  'Tank truck' = TRUCK_TYPE_DEFAULT.TANK_TRUCK,
  'Truck with lift' = TRUCK_TYPE_DEFAULT.WITH_LIFT,
  'Mezzanine van' = TRUCK_TYPE_DEFAULT.MEZZAN,
  'Truck with freezing body' = TRUCK_TYPE_DEFAULT.FREEZING_BODY,
  'Truck with closed body' = TRUCK_TYPE_DEFAULT.CLOSED_BODY,

  'Xe tải nhỏ' = TRUCK_TYPE_DEFAULT.MINI_VAN,
  'Xe tải thùng mui bạt' = TRUCK_TYPE_DEFAULT.TARPAULIN_COVER,
  'Xe tải thùng khung mui bạt' = TRUCK_TYPE_DEFAULT.GRID_AND_TARPAULIN_COVER,
  'Xe tải thùng bạt cánh dơi' = TRUCK_TYPE_DEFAULT.WING_BODY,
  'Xe tải bán hàng lưu động' = TRUCK_TYPE_DEFAULT.FOR_RETAILER,
  'Xe tải không thùng' = TRUCK_TYPE_DEFAULT.WITHOUT_BODY,
  'Xe ben' = TRUCK_TYPE_DEFAULT.DUMP_TRUCK,
  'Xe bồn' = TRUCK_TYPE_DEFAULT.TANK_TRUCK,
  'Xe gắn cẩu' = TRUCK_TYPE_DEFAULT.WITH_LIFT,
  'Xe thùng lửng' = TRUCK_TYPE_DEFAULT.MEZZAN,
  'Xe thùng bảo ôn (đông lạnh)' = TRUCK_TYPE_DEFAULT.FREEZING_BODY,
  'Xe tải thùng kín' = TRUCK_TYPE_DEFAULT.CLOSED_BODY,

  '미니밴' = TRUCK_TYPE_DEFAULT.MINI_VAN,
  '타포린 커버 트럭' = TRUCK_TYPE_DEFAULT.TARPAULIN_COVER,
  '그리드 및 타포린 커버 트럭' = TRUCK_TYPE_DEFAULT.GRID_AND_TARPAULIN_COVER,
  '윙바디 트럭' = TRUCK_TYPE_DEFAULT.WING_BODY,
  '소매업용 트럭' = TRUCK_TYPE_DEFAULT.FOR_RETAILER,
  '차체없는 트럭' = TRUCK_TYPE_DEFAULT.WITHOUT_BODY,
  '덤프 트럭' = TRUCK_TYPE_DEFAULT.DUMP_TRUCK,
  '탱크 트럭' = TRUCK_TYPE_DEFAULT.TANK_TRUCK,
  '리프트 트럭' = TRUCK_TYPE_DEFAULT.WITH_LIFT,
  '메 자닌 밴' = TRUCK_TYPE_DEFAULT.MEZZAN,
  '냉동 트럭' = TRUCK_TYPE_DEFAULT.FREEZING_BODY,
  '폐쇄형 트럭' = TRUCK_TYPE_DEFAULT.CLOSED_BODY,
}

export enum TRUCK_PAYLOAD {
  ANY,
  LESS_THAN_1,
  ONE_TO_TWO,
  TWO_TO_THREE,
  THREE_TO_FOUR,
  FIVE_TO_SIX,
  SIX_TO_EIGHT,
  EIGHT_TO_TEN,
  TEN_TO_FIFTEEN,
  FIFTEEN_TO_TWENTY,
  TWENTY_TO_TWENTY_FIVE,
  TWENTY_FIVE_TO_THIRTY,
  MORE_THAN_THIRTY,
}

export enum TRUCK_PAYLOAD_IMPORT {
  'Any payload' = TRUCK_PAYLOAD.ANY,
  '<1 ton' = TRUCK_PAYLOAD.LESS_THAN_1,
  '1 - 2 tons' = TRUCK_PAYLOAD.ONE_TO_TWO,
  '2 -3 tons' = TRUCK_PAYLOAD.TWO_TO_THREE,
  '3 - 4 tons' = TRUCK_PAYLOAD.THREE_TO_FOUR,
  '5-6 tons' = TRUCK_PAYLOAD.FIVE_TO_SIX,
  '6-8 tons' = TRUCK_PAYLOAD.SIX_TO_EIGHT,
  '8-10 tons' = TRUCK_PAYLOAD.EIGHT_TO_TEN,
  '10-15 tons' = TRUCK_PAYLOAD.TEN_TO_FIFTEEN,
  '15-20 tons' = TRUCK_PAYLOAD.FIFTEEN_TO_TWENTY,
  '20-25 tons' = TRUCK_PAYLOAD.TWENTY_TO_TWENTY_FIVE,
  '25-30 tons' = TRUCK_PAYLOAD.TWENTY_FIVE_TO_THIRTY,
  '>30 tons' = TRUCK_PAYLOAD.MORE_THAN_THIRTY,

  'Bất kì' = TRUCK_PAYLOAD.ANY,
  '<1 tấn' = TRUCK_PAYLOAD.LESS_THAN_1,
  '1 - 2 tấn' = TRUCK_PAYLOAD.ONE_TO_TWO,
  '2 -3 tấn' = TRUCK_PAYLOAD.TWO_TO_THREE,
  '3-4 tấn' = TRUCK_PAYLOAD.THREE_TO_FOUR,
  '5-6 tấn' = TRUCK_PAYLOAD.FIVE_TO_SIX,
  '6-8 tấn' = TRUCK_PAYLOAD.SIX_TO_EIGHT,
  '8-10 tấn' = TRUCK_PAYLOAD.EIGHT_TO_TEN,
  '10-15 tấn' = TRUCK_PAYLOAD.TEN_TO_FIFTEEN,
  '15-20 tấn' = TRUCK_PAYLOAD.FIFTEEN_TO_TWENTY,
  '20-25 tấn' = TRUCK_PAYLOAD.TWENTY_TO_TWENTY_FIVE,
  '25-30 tấn' = TRUCK_PAYLOAD.TWENTY_FIVE_TO_THIRTY,
  '>30 tấn' = TRUCK_PAYLOAD.MORE_THAN_THIRTY,

  '모든 트럭 탑재량' = TRUCK_PAYLOAD.ANY,
  '<1 톤' = TRUCK_PAYLOAD.LESS_THAN_1,
  '1 - 2 톤' = TRUCK_PAYLOAD.ONE_TO_TWO,
  '2 - 3 톤' = TRUCK_PAYLOAD.TWO_TO_THREE,
  '3 - 4 톤' = TRUCK_PAYLOAD.THREE_TO_FOUR,
  '5 - 6 톤' = TRUCK_PAYLOAD.FIVE_TO_SIX,
  '6 - 8 톤' = TRUCK_PAYLOAD.SIX_TO_EIGHT,
  '8 - 10 톤' = TRUCK_PAYLOAD.EIGHT_TO_TEN,
  '10 - 15 톤' = TRUCK_PAYLOAD.TEN_TO_FIFTEEN,
  '15 - 20 톤' = TRUCK_PAYLOAD.FIFTEEN_TO_TWENTY,
  '20 - 25 톤' = TRUCK_PAYLOAD.TWENTY_TO_TWENTY_FIVE,
  '25 - 30 톤' = TRUCK_PAYLOAD.TWENTY_FIVE_TO_THIRTY,
  '>30 톤' = TRUCK_PAYLOAD.MORE_THAN_THIRTY,
}

export enum CONCATENATED_GOODS_TYPE {
  'CARGO_BOX' = 'CARGO_BOX',
  'PACKAGE' = 'PACKAGE',
  'CARGO_COMPARTMENT' = 'CARGO_COMPARTMENT',
  'CARGO_FLOOR' = 'CARGO_FLOOR',
}

export enum CONCATENATED_GOODS_TYPE_FILTER {
  'ANY' = 'ANY',
  'CARGO_BOX' = 'CARGO_BOX',
  'PACKAGE' = 'PACKAGE',
  'CARGO_COMPARTMENT' = 'CARGO_COMPARTMENT',
  'CARGO_FLOOR' = 'CARGO_FLOOR',
}

export enum CONCATENATED_GOODS_TYPE_IMPORT {
  'CARGO_BOX' = 'CARGO_BOX',
  'PACKAGE' = 'PACKAGE',
  'CARGO_COMPARTMENT' = 'CARGO_COMPARTMENT',
  'CARGO_FLOOR' = 'CARGO_FLOOR',

  'Thùng' = 'CARGO_BOX',
  'Kiện' = 'PACKAGE',
  'Khoang' = 'CARGO_COMPARTMENT',
  'Sàn' = 'CARGO_FLOOR',

  'Box' = 'CARGO_BOX',
  'Package' = 'PACKAGE',
  'Compartment' = 'CARGO_COMPARTMENT',
  'Floor' = 'CARGO_FLOOR',
}

export enum CONCATENATED_GOODS_PAYLOAD {
  ANY,
}

export enum CONCATENATED_GOODS_PAYLOAD_IMPORT {
  'Any' = CONCATENATED_GOODS_PAYLOAD.ANY,
  'Bất kì' = CONCATENATED_GOODS_PAYLOAD.ANY,
}

export enum CONTRACT_CAR_TYPE {
  '4_SEATER_CAR' = '4_SEATER_CAR',
  '7_SEATER_CAR' = '7_SEATER_CAR',
  '16_SEATER_CAR' = '16_SEATER_CAR',
}

export enum CONTRACT_CAR_TYPE_FILTER {
  'ANY' = 'ANY',
  '4_SEATER_CAR' = '4_SEATER_CAR',
  '7_SEATER_CAR' = '7_SEATER_CAR',
  '16_SEATER_CAR' = '16_SEATER_CAR',
}

export enum CONTRACT_CAR_TYPE_IMPORT {
  '4_SEATER_CAR' = '4_SEATER_CAR',
  '7_SEATER_CAR' = '7_SEATER_CAR',
  '16_SEATER_CAR' = '16_SEATER_CAR',

  'Xe 4 chỗ' = '4_SEATER_CAR',
  'Xe 7 chỗ' = '7_SEATER_CAR',
  'Xe 16 chỗ' = '16_SEATER_CAR',

  '4 seater car' = '4_SEATER_CAR',
  '7 seater car' = '7_SEATER_CAR',
  '16 seater car' = '16_SEATER_CAR',
}

export enum CONTRACT_CAR_PAYLOAD {
  ANY,
}

export enum CONTRACT_CAR_PAYLOAD_IMPORT {
  'Any' = CONTRACT_CAR_PAYLOAD.ANY,
  'Bất kì' = CONTRACT_CAR_PAYLOAD.ANY,
}
