export enum ADDITIONAL_PROICE_OPTIONS {
  ADJUSTMENT_AMOUNT = 'ADJUSTMENT_AMOUNT',
  FORKLIFT_COST = 'FORKLIFT_COST',
  LABOUR_COST = 'LABOUR_COST',
  ROAD_FEE = 'ROAD_FEE',
  WAITING_FEE = 'WAITING_FEE',
  INCENTIVES = 'INCENTIVES',
  OTHERS = 'OTHERS',
}
