export const TH_CITIES = {
  '01': {
    name: 'Krung Thep',
    slug: 'krung-thep',
    type: 'city',
    name_with_type: 'Krung Thep City',
    code: '01',
  },
  '02': {
    name: 'Nonthaburi',
    slug: 'nonthaburi',
    type: 'city',
    name_with_type: 'Nonthaburi City',
    code: '02',
  },
  '03': {
    name: 'Pak Kret',
    slug: 'pak-kret',
    type: 'city',
    name_with_type: 'Pak Kret City',
    code: '03',
  },
  '04': {
    name: 'Hat Yai',
    slug: 'hat-yai',
    type: 'city',
    name_with_type: 'Hat Yai City',
    code: '04',
  },
  '05': {
    name: 'Chaophraya Surasak',
    slug: 'chaophraya-surasak',
    type: 'city',
    name_with_type: 'Chaophraya Surasak City',
    code: '05',
  },
  '06': {
    name: 'Surat Thani',
    slug: 'surat-thani',
    type: 'city',
    name_with_type: 'Surat Thani City',
    code: '06',
  },
  '07': {
    name: 'Udon Thani',
    slug: 'udon-thani',
    type: 'city',
    name_with_type: 'Udon Thani City',
    code: '07',
  },
  '08': {
    name: 'Chiang Mai',
    slug: 'chiang-mai',
    type: 'city',
    name_with_type: 'Chiang Mai City',
    code: '08',
  },
  '09': {
    name: 'Nakhon Ratchasima',
    slug: 'nakhon-ratchasima',
    type: 'city',
    name_with_type: 'Nakhon Ratchasima City',
    code: '09',
  },
};
