import {
  EMAIL_SUBJECT,
  VI_EMAIL_SUBJECT,
  KR_EMAIL_SUBJECT,
} from './email-title.enum';
import { NOTI_SUBJECT, VI_NOTI_SUBJECT } from './notification.enum';

export const EN_NOTI_MSG = {
  /**
   * Email subject
   */
  EMAIL_SUBJECT_VERIFY_EMAIL: EMAIL_SUBJECT.VERIFY_EMAIL,
  EMAIL_SUBJECT_VERIFY_CHANGE_PASSWORD: EMAIL_SUBJECT.VERIFY_CHANGE_PASSWORD,
  EMAIL_SUBJECT_VERIFY_CHANGE_EMAIL: EMAIL_SUBJECT.VERIFY_CHANGE_EMAIL,
  EMAIL_SUBJECT_VERIFIED_EMAIL: EMAIL_SUBJECT.VERIFIED_EMAIL,
  EMAIL_SUBJECT_PASSWORD_CHANGED: EMAIL_SUBJECT.PASSWORD_CHANGED,
  EMAIL_SUBJECT_TEST: EMAIL_SUBJECT.TEST,
  EMAIL_SUBJECT_FORGOT_PASSWORD: EMAIL_SUBJECT.FORGOT_PASSWORD,
  EMAIL_SUBJECT_EMAIL_WELCOME: EMAIL_SUBJECT.EMAIL_WELCOME,
  EMAIL_SUBJECT_SET_PASSWORD: EMAIL_SUBJECT.SET_PASSWORD,
  EMAIL_SUBJECT_NEW_ORDER: EMAIL_SUBJECT.NEW_ORDER,
  EMAIL_SUBJECT_EDIT_ORDE: EMAIL_SUBJECT.EDIT_ORDER,
  EMAIL_SUBJECT_CANCEL_ORDER: EMAIL_SUBJECT.CANCEL_ORDER,
  EMAIL_SUBJECT_LOOK_FOR_NEW_TRUCK: EMAIL_SUBJECT.LOOK_FOR_NEW_TRUCK,
  EMAIL_SUBJECT_CANCEL_AFTER_ASSIGN: EMAIL_SUBJECT.CANCEL_AFTER_ASSIGN,
  EMAIL_SUBJECT_ASSIGNED_SUCCESS: EMAIL_SUBJECT.ASSIGNED_SUCCESS,
  EMAIL_SUBJECT_CUSTOMER_DRIVER_CANCEL: EMAIL_SUBJECT.CUSTOMER_DRIVER_CANCEL,
  EMAIL_SUBJECT_CUSTOMER_ORDER_COMPLETE: EMAIL_SUBJECT.CUSTOMER_ORDER_COMPLETE,
  EMAIL_SUBJECT_PICKUP_AND_DELIVERY_CODE:
    EMAIL_SUBJECT.PICKUP_AND_DELIVERY_CODE,
  EMAIL_SUBJECT_ACCEPT_ORDER: EMAIL_SUBJECT.ACCEPT_ORDER,
  EMAIL_SUBJECT_CUSTOMER_FIND_NEW_TRUCK: EMAIL_SUBJECT.CUSTOMER_FIND_NEW_TRUCK,
  EMAIL_SUBJECT_CUSTOMER_REQUEST_NEW_TRUCK:
    EMAIL_SUBJECT.CUSTOMER_REQUEST_NEW_TRUCK,
  EMAIL_SUBJECT_CUSTOMER_CANCELLED: EMAIL_SUBJECT.CUSTOMER_CANCELLED,
  EMAIL_SUBJECT_TRUCK_OWNER_DRIVER_CANCEL:
    EMAIL_SUBJECT.TRUCK_OWNER_DRIVER_CANCEL,
  EMAIL_SUBJECT_TRUCK_OWNER_ORDER_COMPLETE:
    EMAIL_SUBJECT.TRUCK_OWNER_ORDER_COMPLETE,
  EMAIL_SUBJECT_FAVORITE_TRUCK: EMAIL_SUBJECT.FAVORITE_TRUCK,
  EMAIL_SUBJECT_TRUCK_CANCELLED_ORDER_SUCCESS:
    EMAIL_SUBJECT.TRUCK_CANCELLED_ORDER_SUCCESS,
  EMAIL_SUBJECT_TRUCK_ASSIGNED_SUCCESS: EMAIL_SUBJECT.TRUCK_ASSIGNED_SUCCESS,

  /**
   * Noti subject
   */
  NOTI_SUBJECT_NEW_ACCOUNT: NOTI_SUBJECT.NEW_ACCOUNT,
  NOTI_SUBJECT_ACCOUNT_VERIFIED: NOTI_SUBJECT.ACCOUNT_VERIFIED,
  NOTI_SUBJECT_EMAIL_VERIFIED: NOTI_SUBJECT.EMAIL_VERIFIED,
  NOTI_SUBJECT_NEW_ORDER: NOTI_SUBJECT.NEW_ORDER,
  NOTI_SUBJECT_EDIT_ORDER: NOTI_SUBJECT.EDIT_ORDER,
  NOTI_SUBJECT_ORDER_ACCEPTED: NOTI_SUBJECT.ORDER_ACCEPTED,
  NOTI_SUBJECT_ORDER_CANCELLED_SUCCESSFULLY:
    NOTI_SUBJECT.ORDER_CANCELLED_SUCCESSFULLY,
  NOTI_SUBJECT_CUSTOMER_FIND_NEW_TRUCK: NOTI_SUBJECT.CUSTOMER_FIND_NEW_TRUCK,
  NOTI_SUBJECT_CANCELLED_BEFORE_ASSIGNED:
    NOTI_SUBJECT.CANCELLED_BEFORE_ASSIGNED,
  NOTI_SUBJECT_CANCELLED_AFTER_ASSIGNED: NOTI_SUBJECT.CANCELLED_AFTER_ASSIGNED,
  NOTI_SUBJECT_ORDER_ASSIGNED_SUCESS: NOTI_SUBJECT.ORDER_ASSIGNED_SUCESS,
  NOTI_SUBJECT_PICKUP_AND_DELIVERY_CODE: NOTI_SUBJECT.PICKUP_AND_DELIVERY_CODE,
  NOTI_SUBJECT_DRIVER_ON_THE_WAY: NOTI_SUBJECT.DRIVER_ON_THE_WAY,
  NOTI_SUBJECT_PICKUP_ARRIVED: NOTI_SUBJECT.PICKUP_ARRIVED,
  NOTI_SUBJECT_PICKUP_CODE: NOTI_SUBJECT.PICKUP_CODE,
  NOTI_SUBJECT_PICKUP_SUCCESSFULLY: NOTI_SUBJECT.PICKUP_SUCCESSFULLY,
  NOTI_SUBJECT_ORDER_ARRIVED: NOTI_SUBJECT.ORDER_ARRIVED,
  NOTI_SUBJECT_DELIVERY_CODE: NOTI_SUBJECT.DELIVERY_CODE,
  NOTI_SUBJECT_ORDER_COMPLETE: NOTI_SUBJECT.ORDER_COMPLETE,
  NOTI_SUBJECT_ADDITIONAL_FARE_ADDED: NOTI_SUBJECT.ADDITIONAL_FARE_ADDED,
  NOTI_SUBJECT_CUSTOMER_SELF_PAYMENT_DONE:
    NOTI_SUBJECT.CUSTOMER_SELF_PAYMENT_DONE,
  NOTI_SUBJECT_TRUCK_PAYMENT_DONE: NOTI_SUBJECT.TRUCK_PAYMENT_DONE,
  NOTI_SUBJECT_ADJUST_FARE: NOTI_SUBJECT.ADJUST_FARE,
  NOTI_SUBJECT_TRUCK_NEW_ORDER: NOTI_SUBJECT.TRUCK_NEW_ORDER,
  NOTI_SUBJECT_TRUCK_ORDER_ACCEPT: NOTI_SUBJECT.TRUCK_ORDER_ACCEPT,
  NOTI_SUBJECT_FIND_NEW_TRUCK: NOTI_SUBJECT.FIND_NEW_TRUCK,
  NOTI_SUBJECT_TRUCK_CUSTOMER_EDIT_ORDER:
    NOTI_SUBJECT.TRUCK_CUSTOMER_EDIT_ORDER,
  NOTI_SUBJECT_TRUCK_CANCELLED_ORDER_SUCCESS:
    NOTI_SUBJECT.TRUCK_CANCELLED_ORDER_SUCCESS,
  NOTI_SUBJECT_CUSTOMER_CANCELLED_ORDER: NOTI_SUBJECT.CUSTOMER_CANCELLED_ORDER,
  NOTI_SUBJECT_TRUCK_ASSIGNED_SUCCESS: NOTI_SUBJECT.TRUCK_ASSIGNED_SUCCESS,
  NOTI_SUBJECT_REMIND_BEFORE_PICKUP: NOTI_SUBJECT.REMIND_BEFORE_PICKUP,
  NOTI_SUBJECT_TRUCK_PICKUP_ARRIVED: NOTI_SUBJECT.TRUCK_PICKUP_ARRIVED,
  NOTI_SUBJECT_ENTER_PICKUP_CODE: NOTI_SUBJECT.ENTER_PICKUP_CODE,
  NOTI_SUBJECT_TRUCK_PICKUP_SUCCESSFULLY:
    NOTI_SUBJECT.TRUCK_PICKUP_SUCCESSFULLY,
  NOTI_SUBJECT_TRUCK_ORDER_ARRIVED: NOTI_SUBJECT.TRUCK_ORDER_ARRIVED,
  NOTI_SUBJECT_ENTER_DELIVERY_CODE: NOTI_SUBJECT.ENTER_DELIVERY_CODE,
  NOTI_SUBJECT_TRUCK_ORDER_COMPLETE: NOTI_SUBJECT.TRUCK_ORDER_COMPLETE,
  NOTI_SUBJECT_FAVORITE_TRUCK: NOTI_SUBJECT.FAVORITE_TRUCK,
  NOTI_SUBJECT_CUSTOMER_ADJUSTED_FARE: NOTI_SUBJECT.CUSTOMER_ADJUSTED_FARE,
  NOTI_SUBJECT_CUSTOMER_PAYMENT_DONE: NOTI_SUBJECT.CUSTOMER_PAYMENT_DONE,
  NOTI_SUBJECT_TRUCK_SELF_PAYMENT_DONE: NOTI_SUBJECT.TRUCK_SELF_PAYMENT_DONE,
  NOTI_SUBJECT_CUSTOMER_ADJUST_FARE: NOTI_SUBJECT.CUSTOMER_ADJUST_FARE,
  NOTI_SUBJECT_LIMIT_ORDER: NOTI_SUBJECT.LIMIT_ORDER,
  NOTI_SUBJECT_TRUCK_DRIVER_ON_THE_WAY: NOTI_SUBJECT.TRUCK_DRIVER_ON_THE_WAY,
};

export const VI_NOTI_MSG = {
  /**
   * Email subject
   */
  EMAIL_SUBJECT_VERIFY_EMAIL: VI_EMAIL_SUBJECT.VERIFY_EMAIL,
  EMAIL_SUBJECT_VERIFIED_EMAIL: VI_EMAIL_SUBJECT.VERIFIED_EMAIL,
  EMAIL_SUBJECT_FORGOT_PASSWORD: VI_EMAIL_SUBJECT.FORGOT_PASSWORD,
  EMAIL_SUBJECT_EMAIL_WELCOME: VI_EMAIL_SUBJECT.EMAIL_WELCOME,
  EMAIL_SUBJECT_SET_PASSWORD: VI_EMAIL_SUBJECT.SET_PASSWORD,
  EMAIL_SUBJECT_NEW_ORDER: VI_EMAIL_SUBJECT.NEW_ORDER,
  EMAIL_SUBJECT_EDIT_ORDE: VI_EMAIL_SUBJECT.EDIT_ORDER,
  EMAIL_SUBJECT_CANCEL_ORDER: VI_EMAIL_SUBJECT.CANCEL_ORDER,
  EMAIL_SUBJECT_LOOK_FOR_NEW_TRUCK: VI_EMAIL_SUBJECT.LOOK_FOR_NEW_TRUCK,
  EMAIL_SUBJECT_CANCEL_AFTER_ASSIGN: VI_EMAIL_SUBJECT.CANCEL_AFTER_ASSIGN,
  EMAIL_SUBJECT_ASSIGNED_SUCCESS: VI_EMAIL_SUBJECT.ASSIGNED_SUCCESS,
  EMAIL_SUBJECT_CUSTOMER_DRIVER_CANCEL: VI_EMAIL_SUBJECT.CUSTOMER_DRIVER_CANCEL,
  EMAIL_SUBJECT_CUSTOMER_ORDER_COMPLETE:
    VI_EMAIL_SUBJECT.CUSTOMER_ORDER_COMPLETE,
  EMAIL_SUBJECT_PICKUP_AND_DELIVERY_CODE:
    VI_EMAIL_SUBJECT.PICKUP_AND_DELIVERY_CODE,
  EMAIL_SUBJECT_ACCEPT_ORDER: VI_EMAIL_SUBJECT.ACCEPT_ORDER,
  EMAIL_SUBJECT_CUSTOMER_FIND_NEW_TRUCK:
    VI_EMAIL_SUBJECT.CUSTOMER_FIND_NEW_TRUCK,
  EMAIL_SUBJECT_CUSTOMER_REQUEST_NEW_TRUCK:
    VI_EMAIL_SUBJECT.CUSTOMER_REQUEST_NEW_TRUCK,
  EMAIL_SUBJECT_CUSTOMER_CANCELLED: VI_EMAIL_SUBJECT.CUSTOMER_CANCELLED,
  EMAIL_SUBJECT_TRUCK_OWNER_DRIVER_CANCEL:
    VI_EMAIL_SUBJECT.TRUCK_OWNER_DRIVER_CANCEL,
  EMAIL_SUBJECT_TRUCK_OWNER_ORDER_COMPLETE:
    VI_EMAIL_SUBJECT.TRUCK_OWNER_ORDER_COMPLETE,
  EMAIL_SUBJECT_FAVORITE_TRUCK: VI_EMAIL_SUBJECT.FAVORITE_TRUCK,
  EMAIL_SUBJECT_TRUCK_CANCELLED_ORDER_SUCCESS:
    VI_EMAIL_SUBJECT.TRUCK_CANCELLED_ORDER_SUCCESS,
  EMAIL_SUBJECT_TRUCK_ASSIGNED_SUCCESS: VI_EMAIL_SUBJECT.TRUCK_ASSIGNED_SUCCESS,

  /**
   * Noti subject
   */
  NOTI_SUBJECT_NEW_ACCOUNT: VI_NOTI_SUBJECT.NEW_ACCOUNT,
  NOTI_SUBJECT_ACCOUNT_VERIFIED: VI_NOTI_SUBJECT.ACCOUNT_VERIFIED,
  NOTI_SUBJECT_EMAIL_VERIFIED: VI_NOTI_SUBJECT.EMAIL_VERIFIED,
  NOTI_SUBJECT_NEW_ORDER: VI_NOTI_SUBJECT.NEW_ORDER,
  NOTI_SUBJECT_EDIT_ORDER: VI_NOTI_SUBJECT.EDIT_ORDER,
  NOTI_SUBJECT_ORDER_ACCEPTED: VI_NOTI_SUBJECT.ORDER_ACCEPTED,
  NOTI_SUBJECT_ORDER_CANCELLED_SUCCESSFULLY:
    VI_NOTI_SUBJECT.ORDER_CANCELLED_SUCCESSFULLY,
  NOTI_SUBJECT_CUSTOMER_FIND_NEW_TRUCK: VI_NOTI_SUBJECT.CUSTOMER_FIND_NEW_TRUCK,
  NOTI_SUBJECT_CANCELLED_BEFORE_ASSIGNED:
    VI_NOTI_SUBJECT.CANCELLED_BEFORE_ASSIGNED,
  NOTI_SUBJECT_CANCELLED_AFTER_ASSIGNED:
    VI_NOTI_SUBJECT.CANCELLED_AFTER_ASSIGNED,
  NOTI_SUBJECT_ORDER_ASSIGNED_SUCESS: VI_NOTI_SUBJECT.ORDER_ASSIGNED_SUCESS,
  NOTI_SUBJECT_PICKUP_AND_DELIVERY_CODE:
    VI_NOTI_SUBJECT.PICKUP_AND_DELIVERY_CODE,
  NOTI_SUBJECT_DRIVER_ON_THE_WAY: VI_NOTI_SUBJECT.DRIVER_ON_THE_WAY,
  NOTI_SUBJECT_PICKUP_ARRIVED: VI_NOTI_SUBJECT.PICKUP_ARRIVED,
  NOTI_SUBJECT_PICKUP_CODE: VI_NOTI_SUBJECT.PICKUP_CODE,
  NOTI_SUBJECT_PICKUP_SUCCESSFULLY: VI_NOTI_SUBJECT.PICKUP_SUCCESSFULLY,
  NOTI_SUBJECT_ORDER_ARRIVED: VI_NOTI_SUBJECT.ORDER_ARRIVED,
  NOTI_SUBJECT_DELIVERY_CODE: VI_NOTI_SUBJECT.DELIVERY_CODE,
  NOTI_SUBJECT_ORDER_COMPLETE: VI_NOTI_SUBJECT.ORDER_COMPLETE,
  NOTI_SUBJECT_TRUCK_NEW_ORDER: VI_NOTI_SUBJECT.TRUCK_NEW_ORDER,
  NOTI_SUBJECT_TRUCK_ORDER_ACCEPT: VI_NOTI_SUBJECT.TRUCK_ORDER_ACCEPT,
  NOTI_SUBJECT_FIND_NEW_TRUCK: VI_NOTI_SUBJECT.FIND_NEW_TRUCK,
  NOTI_SUBJECT_TRUCK_CUSTOMER_EDIT_ORDER:
    VI_NOTI_SUBJECT.TRUCK_CUSTOMER_EDIT_ORDER,
  NOTI_SUBJECT_TRUCK_CANCELLED_ORDER_SUCCESS:
    VI_NOTI_SUBJECT.TRUCK_CANCELLED_ORDER_SUCCESS,
  NOTI_SUBJECT_CUSTOMER_CANCELLED_ORDER:
    VI_NOTI_SUBJECT.CUSTOMER_CANCELLED_ORDER,
  NOTI_SUBJECT_TRUCK_ASSIGNED_SUCCESS: VI_NOTI_SUBJECT.TRUCK_ASSIGNED_SUCCESS,
  NOTI_SUBJECT_REMIND_BEFORE_PICKUP: VI_NOTI_SUBJECT.REMIND_BEFORE_PICKUP,
  NOTI_SUBJECT_TRUCK_PICKUP_ARRIVED: VI_NOTI_SUBJECT.TRUCK_PICKUP_ARRIVED,
  NOTI_SUBJECT_ENTER_PICKUP_CODE: VI_NOTI_SUBJECT.ENTER_PICKUP_CODE,
  NOTI_SUBJECT_TRUCK_PICKUP_SUCCESSFULLY:
    VI_NOTI_SUBJECT.TRUCK_PICKUP_SUCCESSFULLY,
  NOTI_SUBJECT_TRUCK_ORDER_ARRIVED: VI_NOTI_SUBJECT.TRUCK_ORDER_ARRIVED,
  NOTI_SUBJECT_ENTER_DELIVERY_CODE: VI_NOTI_SUBJECT.ENTER_DELIVERY_CODE,
  NOTI_SUBJECT_TRUCK_ORDER_COMPLETE: VI_NOTI_SUBJECT.TRUCK_ORDER_COMPLETE,
  NOTI_SUBJECT_FAVORITE_TRUCK: VI_NOTI_SUBJECT.FAVORITE_TRUCK,
  NOTI_SUBJECT_CUSTOMER_ADJUSTED_FARE: VI_NOTI_SUBJECT.CUSTOMER_ADJUSTED_FARE,
  NOTI_SUBJECT_CUSTOMER_PAYMENT_DONE: VI_NOTI_SUBJECT.CUSTOMER_PAYMENT_DONE,
  NOTI_SUBJECT_TRUCK_SELF_PAYMENT_DONE: VI_NOTI_SUBJECT.TRUCK_SELF_PAYMENT_DONE,
  NOTI_SUBJECT_CUSTOMER_ADJUST_FARE: VI_NOTI_SUBJECT.CUSTOMER_ADJUST_FARE,
  NOTI_SUBJECT_LIMIT_ORDER: VI_NOTI_SUBJECT.LIMIT_ORDER,
  NOTI_SUBJECT_TRUCK_DRIVER_ON_THE_WAY: NOTI_SUBJECT.TRUCK_DRIVER_ON_THE_WAY,
};

export const KR_NOTI_MSG = {
  /**
   * Email subject
   */
  EMAIL_SUBJECT_VERIFY_EMAIL: KR_EMAIL_SUBJECT.VERIFY_EMAIL,
  EMAIL_SUBJECT_VERIFIED_EMAIL: KR_EMAIL_SUBJECT.VERIFIED_EMAIL,
  EMAIL_SUBJECT_FORGOT_PASSWORD: KR_EMAIL_SUBJECT.FORGOT_PASSWORD,
  EMAIL_SUBJECT_EMAIL_WELCOME: KR_EMAIL_SUBJECT.EMAIL_WELCOME,
  EMAIL_SUBJECT_SET_PASSWORD: KR_EMAIL_SUBJECT.SET_PASSWORD,
  EMAIL_SUBJECT_NEW_ORDER: KR_EMAIL_SUBJECT.NEW_ORDER,
  EMAIL_SUBJECT_EDIT_ORDE: KR_EMAIL_SUBJECT.EDIT_ORDER,
  EMAIL_SUBJECT_CANCEL_ORDER: KR_EMAIL_SUBJECT.CANCEL_ORDER,
  EMAIL_SUBJECT_LOOK_FOR_NEW_TRUCK: KR_EMAIL_SUBJECT.LOOK_FOR_NEW_TRUCK,
  EMAIL_SUBJECT_CANCEL_AFTER_ASSIGN: KR_EMAIL_SUBJECT.CANCEL_AFTER_ASSIGN,
  EMAIL_SUBJECT_ASSIGNED_SUCCESS: KR_EMAIL_SUBJECT.ASSIGNED_SUCCESS,
  EMAIL_SUBJECT_CUSTOMER_DRIVER_CANCEL: KR_EMAIL_SUBJECT.CUSTOMER_DRIVER_CANCEL,
  EMAIL_SUBJECT_CUSTOMER_ORDER_COMPLETE:
    KR_EMAIL_SUBJECT.CUSTOMER_ORDER_COMPLETE,
  EMAIL_SUBJECT_PICKUP_AND_DELIVERY_CODE:
    KR_EMAIL_SUBJECT.PICKUP_AND_DELIVERY_CODE,
  EMAIL_SUBJECT_ACCEPT_ORDER: KR_EMAIL_SUBJECT.ACCEPT_ORDER,
  EMAIL_SUBJECT_CUSTOMER_FIND_NEW_TRUCK:
    KR_EMAIL_SUBJECT.CUSTOMER_FIND_NEW_TRUCK,
  EMAIL_SUBJECT_CUSTOMER_REQUEST_NEW_TRUCK:
    KR_EMAIL_SUBJECT.CUSTOMER_REQUEST_NEW_TRUCK,
  EMAIL_SUBJECT_CUSTOMER_CANCELLED: KR_EMAIL_SUBJECT.CUSTOMER_CANCELLED,
  EMAIL_SUBJECT_TRUCK_OWNER_DRIVER_CANCEL:
    KR_EMAIL_SUBJECT.TRUCK_OWNER_DRIVER_CANCEL,
  EMAIL_SUBJECT_TRUCK_OWNER_ORDER_COMPLETE:
    KR_EMAIL_SUBJECT.TRUCK_OWNER_ORDER_COMPLETE,
  EMAIL_SUBJECT_FAVORITE_TRUCK: KR_EMAIL_SUBJECT.FAVORITE_TRUCK,
  EMAIL_SUBJECT_TRUCK_CANCELLED_ORDER_SUCCESS:
    KR_EMAIL_SUBJECT.TRUCK_CANCELLED_ORDER_SUCCESS,
  EMAIL_SUBJECT_CANCELLED_BEFORE_ASSIGNED:
    KR_EMAIL_SUBJECT.CANCELLED_BEFORE_ASSIGNED,
};
