export enum SMS_TYPE {
  ORDER_ACCEPTED = 'ORDER_ACCEPTED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  DRIVER_PICKUP = 'DRIVER_PICKUP',
  DRIVER_DELIVERY = 'DRIVER_DELIVERY',
  ORDER_COMPLETE = 'ORDER_COMPLETE',
}
