export const CUSTOMER_MODULE = 'CUSTOMER';
export enum CUSTOMER_ACTION {
  /*
    UPLOAD RELATED
  */
  UPLOAD_CARD_FRONT = 'UPLOAD_CARD_FRONT',
  UPLOAD_CARD_BACK = 'UPLOAD_CARD_BACK',
  UPLOAD_DRIVER_LICENSE = 'UPLOAD_DRIVER_LICENSE',
  UPLOAD_TRUCK_CERTIFICATE = 'UPLOAD_TRUCK_CERTIFICATE',
  UPLOAD_BUSINESS_LICENSE = 'UPLOAD_BUSINESS_LICENSE',
  UPLOAD_COMPANY_ICON = 'UPLOAD_COMPANY_ICON',

  /*
    PROFILE RELATED
  */
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',

  /*
    FAVORITE TRUCK OWNER RELATED
  */
  RESET_FAVORITE_TRUCK_OWNER = 'RESET_FAVORITE_TRUCK_OWNER',
  REMOVE_FAVORITE_TRUCK_OWNER = 'REMOVE_FAVORITE_TRUCK_OWNER',
  ADD_FAVORITE_TRUCK_OWNER = 'ADD_FAVORITE_TRUCK_OWNER',

  /*
    EMPLOYEE RELATED
  */
  DELETE_EMPLOYEE = 'DELETE_EMPLOYEE',
  CREATE_EMPLOYEE = 'CREATE_EMPLOYEE',

  /*
    COMPANY RELATED
  */
  EDIT_COMPANY = 'EDIT_COMPANY',
  CREATE_COMPANY = 'CREATE_COMPANY',

  /*
    ORDER RELATED
  */
  CREATE_ORDER = 'CREATE_ORDER',
  CANCEL_ORDER = 'CANCEL_ORDER',

  DELETE_FILE = 'DELETE_FILE',
  DELETE_COMPANY_FILE = 'DELETE_COMPANY_FILE',

  SET_PASSWORD = 'SET_PASSWORD',
  EXPORT_ORDER = 'EXPORT_ORDER',
  EXPORT_REPORT = 'EXPORT_REPORT',

  /*
    ADDRESS RELATED
  */
  CREATE_ADDRESS = 'CREATE_ADDRESS',
  UPDATE_ADDRESS = 'UPDATE_ADDRESS',
  DELETE_ADDRESS = 'DELETE_ADDRESS',
  UPDATE_DEFAULT_REF = 'UPDATE_DEFAULT_REF',
  UPDATE_PAYMENT = 'UPDATE_PAYMENT',

  /**
   * PAYMENT DONE
   */
  UPDATE_PAYMENT_DONE = 'UPDATE_PAYMENT_DONE',
}
