export const TRUCK_OWNER_MODULE = 'TRUCK_OWNER';
export enum TRUCK_OWNER_ACTION {
  /*
    UPLOAD RELATED
  */
  UPLOAD_CARD_FRONT = 'UPLOAD_CARD_FRONT',
  UPLOAD_CARD_BACK = 'UPLOAD_CARD_BACK',
  UPLOAD_PROFILE_PICTURE = 'UPLOAD_PROFILE_PICTURE',
  UPLOAD_DRIVER_LICENSE = 'UPLOAD_DRIVER_LICENSE',
  UPLOAD_TRUCK_CERTIFICATE = 'UPLOAD_TRUCK_CERTIFICATE',
  UPLOAD_BUSINESS_LICENSE = 'UPLOAD_BUSINESS_LICENSE',
  UPLOAD_COMPANY_ICON = 'UPLOAD_COMPANY_ICON',
  UPLOAD_DRIVER_CARD_FRONT = 'UPLOAD_DRIVER_CARD_FRONT',
  UPLOAD_DRIVER_CARD_BACK = 'UPLOAD_DRIVER_CARD_BACK',
  UPLOAD_DRIVER_OTHER_DOC = 'UPLOAD_DRIVER_OTHER_DOC',
  UPLOAD_TRUCK_OTHER_DOC = 'UPLOAD_TRUCK_OTHER_DOC',

  /*
    PROFILE RELATED
  */
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',

  /*
    ORDER RELATED
  */
  SEND_TRACKING = 'SEND_TRACKING',

  CREATE_TRUCK = 'CREATE_TRUCK',
  UPDATE_TRUCK = 'UPDATE_TRUCK',
  DETELE_TRUCK = 'DETELE_TRUCK',

  CREATE_DRIVER = 'CREATE_DRIVER',
  UPDATE_DRIVER = 'UPDATE_DRIVER',
  DETELE_DRIVER = 'DETELE_DRIVER',
  TRUCKOWNER_PAYMENT_DRIVER = 'TRUCKOWNER_PAYMENT_DRIVER',

  ACCEPT_ORDER = 'ACCEPT_ORDER',
  ASSIGN_ORDER = 'ASSIGN_ORDER',
  ASSIGN_AND_DISPATCH_ORDER = 'ASSIGN_AND_DISPATCH_ORDER',
  UNTAKE_ORDER = 'UNTAKE_ORDER',
  TAKE_ORDER = 'TAKE_ORDER',

  /*
    COMPANY RELATED
  */
  UPDATE_COMPANY = 'UPDATE_COMPANY',
  CREATE_COMPANY = 'CREATE_COMPANY',

  DELETE_FILE = 'DELETE_FILE',

  ADD_TRUCK_TO_ORDER = 'ADD_TRUCK_TO_ORDER',
  ADD_DRIVER_TO_ORDER = 'ADD_DRIVER_TO_ORDER',
  EXPORT_ORDERS = 'EXPORT_ORDERS',

  /*
    BANK_ACCOUNT RELATED
   */

  CREATE_BANK_ACCOUNT = 'CREATE_BANK_ACCOUNT',
  UPDATE_BANK_ACCOUNT = 'UPDATE_BANK_ACCOUNT',

  /**
   * PAYMENT DONE
   */
  UPDATE_PAYMENT_DONE = 'UPDATE_PAYMENT_DONE',
}
